apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: talos-app
  namespace: argocd
spec:
  syncPolicy:
    automated: {}
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  sources:
  - path: argocd-manifests/dev/workloads/applications
    repoUhRL: https://github.com/Francescoeman/talos-kubernetes-manifests.git
    targetRevision: HEAD
    directory:
      recurse: true
  - path: argocd-manifests/dev/workloads/projects
    repoURL: https://github.com/Francescoeman/talos-kubernetes-manifests.git
    targetRevision: HEAD
    directory:
      recurse: true
