apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-workload-apps-namespaces
  namespace: argocd
spec:
  syncPolicy:
    automated: {}
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: app-manifests/argocd-workload-apps-namespaces/dev
    repoURL: https://github.com/Francescoeman/talos-kubernetes-manifests.git
    targetRevision: HEAD
