apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik
  labels:
    app: traefik
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      containers:
        - name: traefik
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          args:
            - "--api.insecure=true"
            - "--providers.kubernetesingress"
          ports:
            - name: web
              containerPort: 80
            - name: websecure
              containerPort: 443
          resources:
            {{- toYaml .Values.resources | nindent 12 }}