apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: traefik
  labels:
    app: traefik
spec:
  type: {{ .Values.service.type | default "LoadBalancer" }}
  ports:
    - port: 80
      targetPort: 80
      name: web
    - port: 443
      targetPort: 443
      name: websecure
    - port: 9000
      targetPort: 8080
      name: dashboard
  selector:
    app: traefik