apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: talos-example-app-of-apps
  namespace: argocd
spec:
  syncPolicy:
    automated: {}
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  sources:
  - path: argocd-apps/dev
    repoURL: https://github.com/skynetops/talos-example-app.git
    targetRevision: HEAD
    directory:
      recurse: true
