apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespaces
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Francescoeman/talos-kubernetes-manifests
    targetRevision: HEAD
    path: namespaces
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

# filepath: /Users/f.emanuele/Documents/talos-kubernetes-manifests/namespaces/namespaces-app.yaml